import media
import fresh_tomatoes

def animes():
    code_geass = media.Anime("Code Geass","The story is set in an alternative timeline where the world has become split into three superpowers: the Holy Britannian Empire (the Americas; also called Britannia), the Chinese Federation (Asia), and the European Union (Europe and Africa; previously known as the Euro-Universe. Also known as Europa United in Akito the Exiled). The story takes place after the Holy Britannian Empire's conquest of Japan on August 10, 2010 a.t.b., by means of Britannia's newest weapon, the 'Autonomous Armored Knight', or Knightmare Frame.","https://upload.wikimedia.org/wikipedia/en/thumb/0/08/Code_Geass_DVD_Part3.png/220px-Code_Geass_DVD_Part3.png","https://www.youtube.com/watch?v=v-AGjx0N24U")
    nge = media.Anime("Neon Genesis Evangelion","Evangelion is an apocalyptic anime, set in a futuristic Tokyo fifteen years after a worldwide cataclysm. The story centers on Shinji, a teenage boy who is recruited by his father into the shadowy organization NERV to pilot a giant bio-machine mecha called an Evangelion in combat against monstrous beings known as Angels.","https://upload.wikimedia.org/wikipedia/en/thumb/e/e9/EvaBluRayBox.jpg/220px-EvaBluRayBox.jpg","https://www.youtube.com/watch?v=LZKB-6R_D2Q");
    dbz = media.Anime("Dragon Ball Z","Dragon Ball Z picks up five years after the end of the Dragon Ball anime, with Son Goku as a young adult and father to his son Gohan. A humanoid alien named Raditz arrives on Earth in a spacecraft and tracks down Goku, revealing to him that he is his long-lost big brother and that they are members of a nearly extinct extraterrestrial race called the Saiyans","https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Bukkun.png/220px-Bukkun.png","https://www.youtube.com/watch?v=aOPJ6y3HWII")
    digimon = media.Anime("Digimon","Its premise is a group of 7 kids who, while at summer camp, travel to the Digital World, inhabited by creatures known as Digital Monsters, or Digimon, learning they are chosen to be 'DigiDestined' ('Chosen Children' in the Japanese version) to save both the Digital and Real World from evil.","https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Digimon_Digital_Monsters_Season_1_DVD_Cover.png/230px-Digimon_Digital_Monsters_Season_1_DVD_Cover.png","https://www.youtube.com/watch?v=doIw_HM8sa0")
    fmb =media.Anime("Fullmetal Alchemist: Brotherhood","Brothers Edward and Alphonse Elric are raised by their mother Trisha Elric in the remote village of Resembool in the country of Amestris. Their father Hohenheim, a noted and very gifted alchemist, abandoned his family while the boys were still young, and while in Trisha's care they began to show an affinity for alchemy.","https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Fullmetal_Alchemist_Brotherhood.jpg/230px-Fullmetal_Alchemist_Brotherhood.jpg","https://www.youtube.com/watch?v=BOm_PAI2goo")
    death_note=media.Anime("Death Note","Light Yagami is a genius high school student who discovers the 'Death Note', a notebook that kills anyone whose name is written in it. After experimenting with the notebook, Light meets the Shinigami Ryuk, the notebook's original owner, who dropped the notebook to the human world out of boredom. Light tells Ryuk of his plan to rule over a new world free from criminals as a god, where only people he deems morally fit to live remain.","https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/SNote.jpg/230px-SNote.jpg","https://www.youtube.com/watch?v=tJZtOrm-WPk")
    
    fresh_tomatoes.open_movies_page([code_geass,nge,dbz,digimon,fmb,death_note])

animes()